version: '3'
services:
 api-dev:
   build: 
    context: .
    dockerfile: Dockerfile.development
   ports:
    - "8000:8000"
   volumes:
    # Uso un bind mount para el automatic reload al detectar cambios
    - "./:/app"